# Generated by Django 3.2.7 on 2023-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFeedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPredictDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('EDUC', models.CharField(max_length=100)),
                ('SES', models.CharField(max_length=100)),
                ('MMSE', models.CharField(max_length=100)),
                ('CDR', models.CharField(max_length=100)),
                ('eTIV', models.CharField(max_length=100)),
                ('nWBV', models.CharField(max_length=100)),
                ('ASF', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
            ],
        ),
    ]
